language: php


sudo: false

dist: trusty
services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  global:
    - DB_HOST="localhost"
    - DB_USER="root"
    - DB_PASSWORD=""

services:
  - mysql

before_script:
    - composer self-update
    - composer install
    - mysql -e 'CREATE DATABASE nested_set;'

script:
    - bin/phpunit
    - bin/php-cs-fixer fix --dry-run
