name: CI-Unit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.4"

    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: nested_set

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          extensions:  mysqli, pdo_mysql

      - name: "Update deps for newer php versions"
        run: |
          composer config platform.php 8.0
          composer update --no-interaction --no-progress --no-suggest --prefer-dist
        if: "${{ matrix.php-version >= '8.0' }}"

      - name: Prepare project
        run: |
          composer install

      - name: Check
        run: |
          DB_HOST=127.0.0.1 bin/phpunit
